### ISSUE TITLE
Allow custom content types in the Accept header

### ISSUE THREAD

**Issue by agerbens** [synapsestudios/lively#118]
## Allow custom content types in the accept header
Certain endpoints in the Github API have different functionality based on the contents of the `Accept` header. For instance, [List repositories being starred with star creation timestamps](https://developer.github.com/v3/activity/starring/#list-repositories-being-starred-with-star-creation-timestamps)

### Acceptance Criteria
1. The Accept header can have custom content types for particular endpoints, either being entered via the front-end or hardcoded in the lively configs.
1. Any Github endpoints that need this custom Accept header are added to lively configs.

### Tasks
- {{list developer tasks here}}

### Additional Notes
It seems like Github introduces new endpoints to their API and gives people access if they use custom content types in the Accept header. 

As of the creation of this issue, endpoints listed in bullets 1, 3, and 4 on #117 all require this.

**Comment by paulstatezny** [comment]
This is already possible. You can set the `location` of a param to `header`.

Here's how you'd do it for the star creation timestamps example: https://gist.github.com/paulstatezny/cf0d72bec12517d015d4

:boom:
