### ISSUE TITLE
Request URI updated for every endpoint on every response

### ISSUE THREAD

**Issue by zpchavez** [synapsestudios/lively#128]
## Request URI updated for every endpoint on every response

When receiving a new response, the displayed request URI will update for every endpoint, not just the one receiving the new response.

{{screenshot of the problem, include if applicable}}

## Details

- Credentials: {{username / password (remove if not applicable)}}
- URL: {{url where problem occurs, remove if not applicable}}
- Note: {{relevant information like related issues, remove if not applicable}}
- Console Error: {{expand and copy from the console (include line error too), remove if not applicable}}

**Comment by paulstatezny** [comment]
:snowflake: :arrow_up:

**Comment by baohx2000** [comment]
@zpchavez how did you find this is happening?

**Comment by zpchavez** [comment]
I just happened to notice it

**Comment by baohx2000** [comment]
visibly noticed it updating in the browser?  I don't see it happening.  Not sure why it would, with my limited knowledge of react, but it may just be a weird browser redraw thing?  Would be nice if there were a way to actually trigger logging events stating which components change based on state.

**Comment by zpchavez** [comment]
This was either fixed or I dreamed it :boom:
