### ISSUE TITLE
Uploads no longer working

### ISSUE THREAD

**Issue by pedringt** [synapsestudios/lively#148]
## Description

Ref #143

Uploads be broke.

**Comment by zpchavez** [comment]
This is actually happening on an old version that worked previously. ¯\_(ツ)_/¯

**Comment by zpchavez** [comment]
Just tried this on the latest develop and it was working. Confirm? :pray:

**Comment by pedringt** [comment]
:hand:

**Comment by zpchavez** [comment]
:sunny: :arrow_up:

**Comment by pcavagna** [comment]
:+1: 

This works
