### ISSUE TITLE
Older lively style present

### ISSUE THREAD

**Issue by pcavagna** [synapsestudios/lively#149]
## Description

The older lively style is present on develop, may have happened when master and develop were merged.  Appears to be a reversion of changes made in https://github.com/synapsestudios/lively/pull/88.  Hash and array type parameters are missing fields.

![old lively](https://cloud.githubusercontent.com/assets/999600/8221553/e4e5c47e-1514-11e5-9d46-533313c1a28d.jpg)

**Comment by kylecesmat** [comment]
What's broken here? What is the older style?

**Comment by zpchavez** [comment]
Apparently features have regressed too, not just style.

**Comment by zpchavez** [comment]
So I don't think there are any actual feature regressions. We just haven't updates the config files as per the upgrade guide yet in every project. Not sure about the styles. They seem okay to me. Maybe another designer can go over it? This may be a non-issue.

**Comment by zpchavez** [comment]
:boom: Non-issue. See :point_up:
