### ISSUE TITLE
Mention in 1.0 upgrade guide that 'int' needs to become 'integer'.

### ISSUE THREAD

**Issue by zpchavez** [synapsestudios/lively#153]

**Comment by agerbens** [comment]
I don't think `int` was ever a thing. If you used it (or anything other than one of the input types the system recognized) it just defaulted to a text input.

**Comment by baohx2000** [comment]
i believe it was "number" before, which should still be allowed as either an int or float iirc.

**Comment by zpchavez** [comment]
Nevermind then :boom:
